version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017
