version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/:ro

  server:
    container_name: server
    build: ./server
    environment:
      - ADDRESS_DB_URL
    ports:
      - 5000:5000