version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017

  server:
    container_name: server
    build: ./server
    environment:
      - ADDRESS_DB_URL
    ports:
      - 5000:5000

  client:
    container_name: client
    build: ./client
    environment:
      - REACT_APP_AXIOS_URL
    ports:
      - 3000:3000